# Manual steps — run/do these by hand after 01–04.
# (Checklist only; this file is not executed.)

# GitHub SSH key (key is generated by 04):
#   - Add ~/.ssh/id_ed25519.pub to GitHub → Settings → SSH and GPG keys
#   - Repoint dotfiles to SSH so you can push:
#     git -C "$HOME/dotfiles" remote set-url origin git@github.com:jamesgaunt/dotfiles.arch.git

# Install Claude Code (CLI is not installed by the scripts; ~/.claude/settings.json is seeded by 03)

# Rider → sign into JetBrains account → enable Settings Sync (restores keymaps/options/code styles)

# Rider Settings → NuGet: turn off all 3 auto install/update options

# Rider Settings → Tools → Terminal → "Shell path":
#   flatpak-spawn --host script -qc /usr/bin/fish /dev/null
